services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    develop:
      watch:
        - path: .
          target: /code
          action: sync
          #command: >
          #uvicorn main:app --host localhost --port 80 --reload
