services:
  api:
    build: .
    ports:
      - "80:80"
    develop:
      watch:
        - path: .
          target: /code
          action: sync
          #command: >
          #uvicorn main:app --host localhost --port 80 --reload
